// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "ticketflow/services/payment-service/internal/service"
)

// PaymentUseCase is an autogenerated mock type for the PaymentUseCase type
type PaymentUseCase struct {
	mock.Mock
}

// Checkout provides a mock function with given fields: ctx, orderID, provider
func (_m *PaymentUseCase) Checkout(ctx context.Context, orderID string, provider string) (*service.CheckoutResult, error) {
	ret := _m.Called(ctx, orderID, provider)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 *service.CheckoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*service.CheckoutResult, error)); ok {
		return rf(ctx, orderID, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *service.CheckoutResult); ok {
		r0 = rf(ctx, orderID, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CheckoutResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orderID, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleWebhook provides a mock function with given fields: ctx, orderID, status
func (_m *PaymentUseCase) HandleWebhook(ctx context.Context, orderID string, status string) error {
	ret := _m.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentUseCase creates a new instance of PaymentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentUseCase {
	mock := &PaymentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
