// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "ticketflow/services/identity-service/internal/service"

	time "time"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, firebaseIDToken
func (_m *AuthService) Login(ctx context.Context, firebaseIDToken string) (*service.LoginResult, error) {
	ret := _m.Called(ctx, firebaseIDToken)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *service.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.LoginResult, error)); ok {
		return rf(ctx, firebaseIDToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.LoginResult); ok {
		r0 = rf(ctx, firebaseIDToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, firebaseIDToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, jti, accessTokenExpiresAt, refreshToken
func (_m *AuthService) Logout(ctx context.Context, jti string, accessTokenExpiresAt time.Time, refreshToken string) error {
	ret := _m.Called(ctx, jti, accessTokenExpiresAt, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, string) error); ok {
		r0 = rf(ctx, jti, accessTokenExpiresAt, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *AuthService) Refresh(ctx context.Context, refreshToken string) (*service.LoginResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *service.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.LoginResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.LoginResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
