// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pagination "ticketflow/pkg/pagination"

	repository "ticketflow/services/event-service/internal/repository"

	service "ticketflow/services/event-service/internal/service"
)

// EventQueryService is an autogenerated mock type for the EventQueryService type
type EventQueryService struct {
	mock.Mock
}

// GetDetailBySlug provides a mock function with given fields: ctx, slug
func (_m *EventQueryService) GetDetailBySlug(ctx context.Context, slug string) (*service.EventDetail, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailBySlug")
	}

	var r0 *service.EventDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.EventDetail, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.EventDetail); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EventDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPublished provides a mock function with given fields: ctx, filter, p
func (_m *EventQueryService) ListPublished(ctx context.Context, filter repository.EventFilter, p pagination.Params) ([]repository.EventSummaryRow, int64, error) {
	ret := _m.Called(ctx, filter, p)

	if len(ret) == 0 {
		panic("no return value specified for ListPublished")
	}

	var r0 []repository.EventSummaryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.EventFilter, pagination.Params) ([]repository.EventSummaryRow, int64, error)); ok {
		return rf(ctx, filter, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.EventFilter, pagination.Params) []repository.EventSummaryRow); ok {
		r0 = rf(ctx, filter, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventSummaryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.EventFilter, pagination.Params) int64); ok {
		r1 = rf(ctx, filter, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.EventFilter, pagination.Params) error); ok {
		r2 = rf(ctx, filter, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewEventQueryService creates a new instance of EventQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventQueryService {
	mock := &EventQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
