// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "ticketflow/services/event-service/internal/model"

	pagination "ticketflow/pkg/pagination"

	repository "ticketflow/services/event-service/internal/repository"

	service "ticketflow/services/event-service/internal/service"
)

// OrganizerEventService is an autogenerated mock type for the OrganizerEventService type
type OrganizerEventService struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *OrganizerEventService) Cancel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, organizerID, in
func (_m *OrganizerEventService) Create(ctx context.Context, organizerID string, in service.CreateEventInput) (*service.EventDetail, error) {
	ret := _m.Called(ctx, organizerID, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *service.EventDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.CreateEventInput) (*service.EventDetail, error)); ok {
		return rf(ctx, organizerID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.CreateEventInput) *service.EventDetail); ok {
		r0 = rf(ctx, organizerID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EventDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.CreateEventInput) error); ok {
		r1 = rf(ctx, organizerID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailByID provides a mock function with given fields: ctx, id
func (_m *OrganizerEventService) GetDetailByID(ctx context.Context, id string) (*service.EventDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailByID")
	}

	var r0 *service.EventDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.EventDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.EventDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EventDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOwnerID provides a mock function with given fields: ctx, eventID
func (_m *OrganizerEventService) GetOwnerID(ctx context.Context, eventID string) (string, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByOrganizer provides a mock function with given fields: ctx, organizerID, status, p
func (_m *OrganizerEventService) ListByOrganizer(ctx context.Context, organizerID string, status string, p pagination.Params) ([]repository.EventSummaryRow, int64, error) {
	ret := _m.Called(ctx, organizerID, status, p)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrganizer")
	}

	var r0 []repository.EventSummaryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, pagination.Params) ([]repository.EventSummaryRow, int64, error)); ok {
		return rf(ctx, organizerID, status, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, pagination.Params) []repository.EventSummaryRow); ok {
		r0 = rf(ctx, organizerID, status, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventSummaryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, pagination.Params) int64); ok {
		r1 = rf(ctx, organizerID, status, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, pagination.Params) error); ok {
		r2 = rf(ctx, organizerID, status, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Publish provides a mock function with given fields: ctx, id
func (_m *OrganizerEventService) Publish(ctx context.Context, id string) (*model.Event, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Event, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Event); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *OrganizerEventService) Update(ctx context.Context, id string, in service.UpdateEventInput) (*service.EventDetail, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *service.EventDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.UpdateEventInput) (*service.EventDetail, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.UpdateEventInput) *service.EventDetail); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EventDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.UpdateEventInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizerEventService creates a new instance of OrganizerEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizerEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizerEventService {
	mock := &OrganizerEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
