// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "ticketflow/services/event-service/internal/model"

	service "ticketflow/services/event-service/internal/service"
)

// TicketTypeCreator is an autogenerated mock type for the TicketTypeCreator type
type TicketTypeCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, eventID, in
func (_m *TicketTypeCreator) Create(ctx context.Context, eventID string, in service.CreateTicketTypeInput) (*model.TicketType, error) {
	ret := _m.Called(ctx, eventID, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.TicketType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.CreateTicketTypeInput) (*model.TicketType, error)); ok {
		return rf(ctx, eventID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.CreateTicketTypeInput) *model.TicketType); ok {
		r0 = rf(ctx, eventID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TicketType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.CreateTicketTypeInput) error); ok {
		r1 = rf(ctx, eventID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTicketTypeCreator creates a new instance of TicketTypeCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketTypeCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketTypeCreator {
	mock := &TicketTypeCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
