// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SessionChecker is an autogenerated mock type for the SessionChecker type
type SessionChecker struct {
	mock.Mock
}

// CheckSession provides a mock function with given fields: ctx, jti, userID
func (_m *SessionChecker) CheckSession(ctx context.Context, jti string, userID string) (bool, string, error) {
	ret := _m.Called(ctx, jti, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckSession")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, string, error)); ok {
		return rf(ctx, jti, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, jti, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, jti, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, jti, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewSessionChecker creates a new instance of SessionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionChecker {
	mock := &SessionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
