// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: booking.proto

package bookingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	BookingService_GetOrder_FullMethodName            = "/ticketflow.booking.BookingService/GetOrder"
	BookingService_ConfirmOrderPayment_FullMethodName = "/ticketflow.booking.BookingService/ConfirmOrderPayment"
	BookingService_FailOrderPayment_FullMethodName    = "/ticketflow.booking.BookingService/FailOrderPayment"
)

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BookingService exposes internal-only RPCs consumed by payment-service.
// The public contract lives in api-docs/openapi/booking-service.yaml.
type BookingServiceClient interface {
	// GetOrder lets payment-service validate an order exists/is pending and
	// read its amount before starting a checkout session.
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*OrderSummary, error)
	// ConfirmOrderPayment is called by payment-service after a (mocked, in
	// Phase 1) successful payment. booking-service transitions
	// orders.status pending->paid and generates tickets in its own transaction.
	ConfirmOrderPayment(ctx context.Context, in *ConfirmOrderPaymentRequest, opts ...grpc.CallOption) (*ConfirmOrderPaymentResponse, error)
	// FailOrderPayment runs the compensating transaction: restores sold_count
	// and transitions orders.status to cancelled.
	FailOrderPayment(ctx context.Context, in *FailOrderPaymentRequest, opts ...grpc.CallOption) (*OrderSummary, error)
}

type bookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingServiceClient(cc grpc.ClientConnInterface) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*OrderSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderSummary)
	err := c.cc.Invoke(ctx, BookingService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) ConfirmOrderPayment(ctx context.Context, in *ConfirmOrderPaymentRequest, opts ...grpc.CallOption) (*ConfirmOrderPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmOrderPaymentResponse)
	err := c.cc.Invoke(ctx, BookingService_ConfirmOrderPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) FailOrderPayment(ctx context.Context, in *FailOrderPaymentRequest, opts ...grpc.CallOption) (*OrderSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderSummary)
	err := c.cc.Invoke(ctx, BookingService_FailOrderPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
// All implementations must embed UnimplementedBookingServiceServer
// for forward compatibility
//
// BookingService exposes internal-only RPCs consumed by payment-service.
// The public contract lives in api-docs/openapi/booking-service.yaml.
type BookingServiceServer interface {
	// GetOrder lets payment-service validate an order exists/is pending and
	// read its amount before starting a checkout session.
	GetOrder(context.Context, *GetOrderRequest) (*OrderSummary, error)
	// ConfirmOrderPayment is called by payment-service after a (mocked, in
	// Phase 1) successful payment. booking-service transitions
	// orders.status pending->paid and generates tickets in its own transaction.
	ConfirmOrderPayment(context.Context, *ConfirmOrderPaymentRequest) (*ConfirmOrderPaymentResponse, error)
	// FailOrderPayment runs the compensating transaction: restores sold_count
	// and transitions orders.status to cancelled.
	FailOrderPayment(context.Context, *FailOrderPaymentRequest) (*OrderSummary, error)
	mustEmbedUnimplementedBookingServiceServer()
}

// UnimplementedBookingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookingServiceServer struct {
}

func (UnimplementedBookingServiceServer) GetOrder(context.Context, *GetOrderRequest) (*OrderSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedBookingServiceServer) ConfirmOrderPayment(context.Context, *ConfirmOrderPaymentRequest) (*ConfirmOrderPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmOrderPayment not implemented")
}
func (UnimplementedBookingServiceServer) FailOrderPayment(context.Context, *FailOrderPaymentRequest) (*OrderSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailOrderPayment not implemented")
}
func (UnimplementedBookingServiceServer) mustEmbedUnimplementedBookingServiceServer() {}

// UnsafeBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServiceServer will
// result in compilation errors.
type UnsafeBookingServiceServer interface {
	mustEmbedUnimplementedBookingServiceServer()
}

func RegisterBookingServiceServer(s grpc.ServiceRegistrar, srv BookingServiceServer) {
	s.RegisterService(&BookingService_ServiceDesc, srv)
}

func _BookingService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_ConfirmOrderPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmOrderPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).ConfirmOrderPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_ConfirmOrderPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).ConfirmOrderPayment(ctx, req.(*ConfirmOrderPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_FailOrderPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailOrderPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).FailOrderPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_FailOrderPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).FailOrderPayment(ctx, req.(*FailOrderPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingService_ServiceDesc is the grpc.ServiceDesc for BookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticketflow.booking.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _BookingService_GetOrder_Handler,
		},
		{
			MethodName: "ConfirmOrderPayment",
			Handler:    _BookingService_ConfirmOrderPayment_Handler,
		},
		{
			MethodName: "FailOrderPayment",
			Handler:    _BookingService_FailOrderPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking.proto",
}
