// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ticketflow/services/event-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// CatalogRepository is an autogenerated mock type for the CatalogRepository type
type CatalogRepository struct {
	mock.Mock
}

// GetByEventID provides a mock function with given fields: ctx, eventID
func (_m *CatalogRepository) GetByEventID(ctx context.Context, eventID string) (*model.EventCatalog, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByEventID")
	}

	var r0 *model.EventCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.EventCatalog, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.EventCatalog); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EventCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, doc
func (_m *CatalogRepository) Upsert(ctx context.Context, doc *model.EventCatalog) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.EventCatalog) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCatalogRepository creates a new instance of CatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogRepository {
	mock := &CatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
