// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "ticketflow/services/event-service/internal/model"

	pagination "ticketflow/pkg/pagination"

	repository "ticketflow/services/event-service/internal/repository"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

// CreateTx provides a mock function with given fields: tx, e
func (_m *EventRepository) CreateTx(tx *gorm.DB, e *model.Event) error {
	ret := _m.Called(tx, e)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.Event) error); ok {
		r0 = rf(tx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB provides a mock function with no fields
func (_m *EventRepository) DB() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *EventRepository) GetByID(ctx context.Context, id string) (*model.Event, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Event, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Event); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublishedBySlug provides a mock function with given fields: ctx, slug
func (_m *EventRepository) GetPublishedBySlug(ctx context.Context, slug string) (*model.Event, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedBySlug")
	}

	var r0 *model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Event, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Event); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByOrganizer provides a mock function with given fields: ctx, organizerID, status, p
func (_m *EventRepository) ListByOrganizer(ctx context.Context, organizerID string, status string, p pagination.Params) ([]repository.EventSummaryRow, int64, error) {
	ret := _m.Called(ctx, organizerID, status, p)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrganizer")
	}

	var r0 []repository.EventSummaryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, pagination.Params) ([]repository.EventSummaryRow, int64, error)); ok {
		return rf(ctx, organizerID, status, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, pagination.Params) []repository.EventSummaryRow); ok {
		r0 = rf(ctx, organizerID, status, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventSummaryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, pagination.Params) int64); ok {
		r1 = rf(ctx, organizerID, status, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, pagination.Params) error); ok {
		r2 = rf(ctx, organizerID, status, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListPublished provides a mock function with given fields: ctx, filter, p
func (_m *EventRepository) ListPublished(ctx context.Context, filter repository.EventFilter, p pagination.Params) ([]repository.EventSummaryRow, int64, error) {
	ret := _m.Called(ctx, filter, p)

	if len(ret) == 0 {
		panic("no return value specified for ListPublished")
	}

	var r0 []repository.EventSummaryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.EventFilter, pagination.Params) ([]repository.EventSummaryRow, int64, error)); ok {
		return rf(ctx, filter, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.EventFilter, pagination.Params) []repository.EventSummaryRow); ok {
		r0 = rf(ctx, filter, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventSummaryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.EventFilter, pagination.Params) int64); ok {
		r1 = rf(ctx, filter, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.EventFilter, pagination.Params) error); ok {
		r2 = rf(ctx, filter, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SlugExists provides a mock function with given fields: ctx, slug
func (_m *EventRepository) SlugExists(ctx context.Context, slug string) (bool, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for SlugExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, e
func (_m *EventRepository) Update(ctx context.Context, e *model.Event) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Event) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
