// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ticketflow/services/event-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TicketTypeWriter is an autogenerated mock type for the TicketTypeWriter type
type TicketTypeWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tt
func (_m *TicketTypeWriter) Create(ctx context.Context, tt *model.TicketType) error {
	ret := _m.Called(ctx, tt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TicketType) error); ok {
		r0 = rf(ctx, tt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTicketTypeWriter creates a new instance of TicketTypeWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketTypeWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketTypeWriter {
	mock := &TicketTypeWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
