// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ticketflow/services/event-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TicketTypeRepository is an autogenerated mock type for the TicketTypeRepository type
type TicketTypeRepository struct {
	mock.Mock
}

// ListByEventID provides a mock function with given fields: ctx, eventID
func (_m *TicketTypeRepository) ListByEventID(ctx context.Context, eventID string) ([]model.TicketType, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListByEventID")
	}

	var r0 []model.TicketType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.TicketType, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.TicketType); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TicketType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTicketTypeRepository creates a new instance of TicketTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketTypeRepository {
	mock := &TicketTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
