// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	bookingclient "ticketflow/services/payment-service/internal/bookingclient"

	mock "github.com/stretchr/testify/mock"
)

// BookingClient is an autogenerated mock type for the BookingClient type
type BookingClient struct {
	mock.Mock
}

// ConfirmOrderPayment provides a mock function with given fields: ctx, orderID, paymentID
func (_m *BookingClient) ConfirmOrderPayment(ctx context.Context, orderID string, paymentID string) (*bookingclient.ConfirmResult, error) {
	ret := _m.Called(ctx, orderID, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOrderPayment")
	}

	var r0 *bookingclient.ConfirmResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*bookingclient.ConfirmResult, error)); ok {
		return rf(ctx, orderID, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *bookingclient.ConfirmResult); ok {
		r0 = rf(ctx, orderID, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingclient.ConfirmResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orderID, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FailOrderPayment provides a mock function with given fields: ctx, orderID, paymentID, reason
func (_m *BookingClient) FailOrderPayment(ctx context.Context, orderID string, paymentID string, reason string) (*bookingclient.ConfirmResult, error) {
	ret := _m.Called(ctx, orderID, paymentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for FailOrderPayment")
	}

	var r0 *bookingclient.ConfirmResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*bookingclient.ConfirmResult, error)); ok {
		return rf(ctx, orderID, paymentID, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *bookingclient.ConfirmResult); ok {
		r0 = rf(ctx, orderID, paymentID, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingclient.ConfirmResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, orderID, paymentID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, orderID
func (_m *BookingClient) GetOrder(ctx context.Context, orderID string) (*bookingclient.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *bookingclient.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*bookingclient.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *bookingclient.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookingclient.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookingClient creates a new instance of BookingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingClient {
	mock := &BookingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
