// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ticketflow/services/payment-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// PaymentStore is an autogenerated mock type for the PaymentStore type
type PaymentStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, p
func (_m *PaymentStore) Create(ctx context.Context, p *model.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLatestByOrderID provides a mock function with given fields: ctx, orderID
func (_m *PaymentStore) GetLatestByOrderID(ctx context.Context, orderID string) (*model.Payment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByOrderID")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, providerTxnID
func (_m *PaymentStore) UpdateStatus(ctx context.Context, id string, status string, providerTxnID *string) error {
	ret := _m.Called(ctx, id, status, providerTxnID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) error); ok {
		r0 = rf(ctx, id, status, providerTxnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentStore creates a new instance of PaymentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentStore {
	mock := &PaymentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
