// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	eventclient "ticketflow/services/booking-service/internal/eventclient"

	mock "github.com/stretchr/testify/mock"
)

// EventChecker is an autogenerated mock type for the EventChecker type
type EventChecker struct {
	mock.Mock
}

// GetEvent provides a mock function with given fields: ctx, eventID
func (_m *EventChecker) GetEvent(ctx context.Context, eventID string) (*eventclient.Event, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *eventclient.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eventclient.Event, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eventclient.Event); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eventclient.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventChecker creates a new instance of EventChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventChecker {
	mock := &EventChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
