// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	lock "ticketflow/services/booking-service/internal/lock"

	mock "github.com/stretchr/testify/mock"
)

// Locker is an autogenerated mock type for the Locker type
type Locker struct {
	mock.Mock
}

// AcquireMany provides a mock function with given fields: ctx, ticketTypeIDs
func (_m *Locker) AcquireMany(ctx context.Context, ticketTypeIDs []string) (lock.Unlock, error) {
	ret := _m.Called(ctx, ticketTypeIDs)

	if len(ret) == 0 {
		panic("no return value specified for AcquireMany")
	}

	var r0 lock.Unlock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (lock.Unlock, error)); ok {
		return rf(ctx, ticketTypeIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) lock.Unlock); ok {
		r0 = rf(ctx, ticketTypeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lock.Unlock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ticketTypeIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLocker creates a new instance of Locker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Locker {
	mock := &Locker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
