// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ticketflow/services/booking-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ConfirmPayment provides a mock function with given fields: ctx, orderID
func (_m *Repository) ConfirmPayment(ctx context.Context, orderID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPayment")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: ctx, userID, items
func (_m *Repository) CreateOrder(ctx context.Context, userID string, items []model.BookingItem) (*model.Order, error) {
	ret := _m.Called(ctx, userID, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.BookingItem) (*model.Order, error)); ok {
		return rf(ctx, userID, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.BookingItem) *model.Order); ok {
		r0 = rf(ctx, userID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []model.BookingItem) error); ok {
		r1 = rf(ctx, userID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FailPayment provides a mock function with given fields: ctx, orderID
func (_m *Repository) FailPayment(ctx context.Context, orderID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FailPayment")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventIDsForTicketTypes provides a mock function with given fields: ctx, ticketTypeIDs
func (_m *Repository) GetEventIDsForTicketTypes(ctx context.Context, ticketTypeIDs []string) (map[string]string, error) {
	ret := _m.Called(ctx, ticketTypeIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetEventIDsForTicketTypes")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return rf(ctx, ticketTypeIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = rf(ctx, ticketTypeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ticketTypeIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetOrderByID(ctx context.Context, id string) (*model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrdersByUser provides a mock function with given fields: ctx, userID, status, limit, offset
func (_m *Repository) ListOrdersByUser(ctx context.Context, userID string, status string, limit int, offset int) ([]*model.Order, int64, error) {
	ret := _m.Called(ctx, userID, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListOrdersByUser")
	}

	var r0 []*model.Order
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*model.Order, int64, error)); ok {
		return rf(ctx, userID, status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*model.Order); ok {
		r0 = rf(ctx, userID, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int64); ok {
		r1 = rf(ctx, userID, status, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, userID, status, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
