// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "ticketflow/services/booking-service/internal/model"

	pagination "ticketflow/pkg/pagination"
)

// Bookings is an autogenerated mock type for the Bookings type
type Bookings struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, userID, items
func (_m *Bookings) CreateOrder(ctx context.Context, userID string, items []model.BookingItem) (*model.Order, error) {
	ret := _m.Called(ctx, userID, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.BookingItem) (*model.Order, error)); ok {
		return rf(ctx, userID, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.BookingItem) *model.Order); ok {
		r0 = rf(ctx, userID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []model.BookingItem) error); ok {
		r1 = rf(ctx, userID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, id
func (_m *Bookings) GetOrderByID(ctx context.Context, id string) (*model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOwnerID provides a mock function with given fields: ctx, orderID
func (_m *Bookings) GetOwnerID(ctx context.Context, orderID string) (string, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMyOrders provides a mock function with given fields: ctx, userID, status, p
func (_m *Bookings) ListMyOrders(ctx context.Context, userID string, status string, p pagination.Params) ([]*model.Order, int64, error) {
	ret := _m.Called(ctx, userID, status, p)

	if len(ret) == 0 {
		panic("no return value specified for ListMyOrders")
	}

	var r0 []*model.Order
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, pagination.Params) ([]*model.Order, int64, error)); ok {
		return rf(ctx, userID, status, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, pagination.Params) []*model.Order); ok {
		r0 = rf(ctx, userID, status, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, pagination.Params) int64); ok {
		r1 = rf(ctx, userID, status, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, pagination.Params) error); ok {
		r2 = rf(ctx, userID, status, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewBookings creates a new instance of Bookings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookings(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bookings {
	mock := &Bookings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
